"""
Pre-written, expert-reviewed content selected by tier and risk factors.
NOT generated by LLM — deterministic selection for safety.
Multi-language support: en, zh, ms, ta.
"""

import json

# ── Exercise Plans by Tier (multi-language) ─────────────────────────────

_EXERCISE_PLANS_I18N: dict[str, dict[str, dict]] = {
    "en": {
        "robust": {
            "title": "Maintenance Exercise Plan",
            "frequency": "Daily, 20-30 minutes",
            "exercises": ["chair-stand", "wall-push", "heel-raise", "marching", "leg-extensions", "shoulder-rolls"],
            "description": "Keep your strength and balance at their best with this well-rounded routine.",
            "notes": "You're doing well! These exercises maintain your current fitness level.",
        },
        "pre_frail": {
            "title": "Strengthening Exercise Plan",
            "frequency": "Daily, 15-20 minutes",
            "exercises": ["chair-stand", "heel-raise", "marching", "sit-to-stand-hold", "ankle-circles", "shoulder-rolls"],
            "description": "Build strength in the areas that need it most, focusing on balance and leg power.",
            "notes": "Start gently and build up. Rest whenever you need to.",
        },
        "frail": {
            "title": "Gentle Exercise Plan",
            "frequency": "Daily, 10-15 minutes",
            "exercises": ["ankle-circles", "shoulder-rolls", "heel-raise", "marching"],
            "description": "Gentle seated and standing exercises to improve mobility safely.",
            "notes": "Go at your own pace. Use a chair for support. Stop if you feel dizzy.",
        },
        "severely_frail": {
            "title": "Supported Exercise Plan",
            "frequency": "Daily, 5-10 minutes with caregiver",
            "exercises": ["ankle-circles", "shoulder-rolls"],
            "description": "Simple exercises with caregiver support to maintain mobility.",
            "notes": "Have your caregiver or family member nearby. Very gentle movements only.",
        },
    },
    "zh": {
        "robust": {
            "title": "保持运动计划",
            "frequency": "每天 20-30 分钟",
            "exercises": ["chair-stand", "wall-push", "heel-raise", "marching", "leg-extensions", "shoulder-rolls"],
            "description": "通过全面的运动来保持您的力量和平衡。",
            "notes": "您做得很好！这些运动帮助维持您目前的健康水平。",
        },
        "pre_frail": {
            "title": "增强力量运动计划",
            "frequency": "每天 15-20 分钟",
            "exercises": ["chair-stand", "heel-raise", "marching", "sit-to-stand-hold", "ankle-circles", "shoulder-rolls"],
            "description": "重点加强平衡和腿部力量。",
            "notes": "慢慢来，循序渐进。累了就休息。",
        },
        "frail": {
            "title": "温和运动计划",
            "frequency": "每天 10-15 分钟",
            "exercises": ["ankle-circles", "shoulder-rolls", "heel-raise", "marching"],
            "description": "温和的坐姿和站姿运动，安全地改善行动能力。",
            "notes": "按自己的节奏来。可以扶着椅子。如果感到头晕就停下来。",
        },
        "severely_frail": {
            "title": "辅助运动计划",
            "frequency": "每天 5-10 分钟（需要照护者陪同）",
            "exercises": ["ankle-circles", "shoulder-rolls"],
            "description": "在照护者帮助下进行简单运动以维持行动能力。",
            "notes": "请让照护者或家人在旁边。只做非常轻柔的动作。",
        },
    },
    "ms": {
        "robust": {
            "title": "Pelan Senaman Penyelenggaraan",
            "frequency": "Setiap hari, 20-30 minit",
            "exercises": ["chair-stand", "wall-push", "heel-raise", "marching", "leg-extensions", "shoulder-rolls"],
            "description": "Kekalkan kekuatan dan keseimbangan anda dengan rutin menyeluruh ini.",
            "notes": "Anda bagus! Senaman ini mengekalkan tahap kecergasan anda.",
        },
        "pre_frail": {
            "title": "Pelan Senaman Pengukuhan",
            "frequency": "Setiap hari, 15-20 minit",
            "exercises": ["chair-stand", "heel-raise", "marching", "sit-to-stand-hold", "ankle-circles", "shoulder-rolls"],
            "description": "Kukuhkan keseimbangan dan kekuatan kaki anda.",
            "notes": "Mula perlahan dan tingkatkan secara beransur. Rehat bila perlu.",
        },
        "frail": {
            "title": "Pelan Senaman Lembut",
            "frequency": "Setiap hari, 10-15 minit",
            "exercises": ["ankle-circles", "shoulder-rolls", "heel-raise", "marching"],
            "description": "Senaman duduk dan berdiri yang lembut untuk meningkatkan mobiliti.",
            "notes": "Ikut rentak sendiri. Guna kerusi untuk sokongan. Berhenti jika pening.",
        },
        "severely_frail": {
            "title": "Pelan Senaman Bersokongan",
            "frequency": "Setiap hari, 5-10 minit dengan penjaga",
            "exercises": ["ankle-circles", "shoulder-rolls"],
            "description": "Senaman mudah dengan sokongan penjaga untuk kekalkan mobiliti.",
            "notes": "Pastikan penjaga atau ahli keluarga ada berdekatan. Pergerakan sangat lembut sahaja.",
        },
    },
    "ta": {
        "robust": {
            "title": "பராமரிப்பு உடற்பயிற்சி திட்டம்",
            "frequency": "தினமும் 20-30 நிமிடங்கள்",
            "exercises": ["chair-stand", "wall-push", "heel-raise", "marching", "leg-extensions", "shoulder-rolls"],
            "description": "இந்த முழுமையான பயிற்சியால் உங்கள் வலிமையையும் சமநிலையையும் பராமரியுங்கள்.",
            "notes": "நீங்கள் நன்றாக செய்கிறீர்கள்! இந்த பயிற்சிகள் உங்கள் தற்போதைய உடற்தகுதியை பராமரிக்கின்றன.",
        },
        "pre_frail": {
            "title": "வலிமைப்படுத்தும் உடற்பயிற்சி திட்டம்",
            "frequency": "தினமும் 15-20 நிமிடங்கள்",
            "exercises": ["chair-stand", "heel-raise", "marching", "sit-to-stand-hold", "ankle-circles", "shoulder-rolls"],
            "description": "சமநிலை மற்றும் கால் வலிமையில் கவனம் செலுத்துங்கள்.",
            "notes": "மெதுவாக தொடங்கி படிப்படியாக அதிகரியுங்கள். தேவைப்படும்போது ஓய்வெடுங்கள்.",
        },
        "frail": {
            "title": "மென்மையான உடற்பயிற்சி திட்டம்",
            "frequency": "தினமும் 10-15 நிமிடங்கள்",
            "exercises": ["ankle-circles", "shoulder-rolls", "heel-raise", "marching"],
            "description": "நகர்வுத்திறனை பாதுகாப்பாக மேம்படுத்த மென்மையான பயிற்சிகள்.",
            "notes": "உங்கள் வேகத்தில் செய்யுங்கள். நாற்காலியை பிடியுங்கள். தலைச்சுற்றல் வந்தால் நிறுத்துங்கள்.",
        },
        "severely_frail": {
            "title": "ஆதரவு உடற்பயிற்சி திட்டம்",
            "frequency": "தினமும் 5-10 நிமிடங்கள் (பராமரிப்பாளருடன்)",
            "exercises": ["ankle-circles", "shoulder-rolls"],
            "description": "நகர்வுத்திறனை பராமரிக்க பராமரிப்பாளர் ஆதரவுடன் எளிய பயிற்சிகள்.",
            "notes": "பராமரிப்பாளர் அல்லது குடும்பத்தினர் அருகில் இருக்கட்டும். மிக மென்மையான அசைவுகள் மட்டும்.",
        },
    },
}

# Backward-compatible alias (English)
EXERCISE_PLANS: dict[str, dict] = _EXERCISE_PLANS_I18N["en"]


def _get_lang_plans(language: str = "en") -> dict[str, dict]:
    """Get exercise plans for a given language, fallback to English."""
    lang = language.lower()[:2] if language else "en"
    return _EXERCISE_PLANS_I18N.get(lang, _EXERCISE_PLANS_I18N["en"])

# ── Deficit-Specific Exercises ──────────────────────────────────────────

DEFICIT_EXERCISES: dict[str, list[str]] = {
    "low_balance": ["heel-raise", "ankle-circles"],
    "slow_gait": ["marching", "heel-raise"],
    "weak_chair_stand": ["chair-stand", "sit-to-stand-hold", "leg-extensions"],
}

# ── Issue-to-Exercise Mapping ──────────────────────────────────────────

ISSUE_EXERCISES: dict[str, list[str]] = {
    "sway": ["heel-raise", "ankle-circles"],
    "lateral_sway": ["heel-raise", "ankle-circles"],
    "unsteady_turns": ["heel-raise", "marching"],
    "slow_speed": ["marching", "chair-stand"],
    "shuffling": ["marching", "leg-extensions"],
    "poor_sit_to_stand": ["chair-stand", "sit-to-stand-hold"],
    "excessive_trunk_lean": ["wall-push", "shoulder-rolls"],
    "reduced_arm_swing": ["shoulder-rolls", "marching"],
    "wide_base": ["heel-raise", "ankle-circles"],
    "asymmetry": ["marching", "heel-raise"],
    "hesitation": ["marching", "ankle-circles"],
}

# ── Sleep Content by Risk ──────────────────────────────────────────────

SLEEP_CONTENT: dict[str, str] = {
    "low": (
        "Your sleep seems healthy! Keep up your good habits:\n"
        "• Stick to a regular sleep schedule\n"
        "• Get sunlight during the day\n"
        "• Stay active with your exercises"
    ),
    "moderate": (
        "Here are some tips to improve your sleep:\n"
        "• Go to bed and wake up at the same time every day\n"
        "• Avoid screens 1 hour before bed\n"
        "• Keep your room cool and dark\n"
        "• Try gentle stretching before bed\n"
        "• Limit coffee and tea after 2pm\n"
        "• If you nap, keep it to 20 minutes before 3pm"
    ),
    "high": (
        "Sleep difficulties can affect your recovery and strength. Consider these steps:\n\n"
        "**Sleep Hygiene Basics:**\n"
        "• Fixed wake time — same time every day, even weekends\n"
        "• Bed is for sleep only — don't watch TV or use phone in bed\n"
        "• Get bright light in the morning\n\n"
        "**Relaxation Techniques:**\n"
        "• Deep breathing: breathe in for 4 counts, out for 6\n"
        "• Progressive muscle relaxation before bed\n"
        "• Warm drink (no caffeine) 1 hour before bed\n\n"
        "**When to Seek Help:**\n"
        "If sleep problems last more than 2 weeks, talk to your doctor or polyclinic."
    ),
}

# ── Education Content ──────────────────────────────────────────────────

EDUCATION_CONTENT: dict[str, dict[str, str]] = {
    "frailty": {
        "robust": (
            "You're in good shape! 'Robust' means your body is strong and you can do daily tasks well. "
            "Keep exercising and eating well to stay this way."
        ),
        "pre_frail": (
            "Being 'pre-frail' means your body is showing some early signs of slowing down. "
            "The good news: with regular exercise and good nutrition, many people improve and become robust again. "
            "Your exercises are designed to help with exactly this."
        ),
        "frail": (
            "Being 'frail' means your body needs extra care right now. This doesn't mean things can't improve. "
            "Gentle daily exercises, good nutrition (especially protein), and staying socially active all help. "
            "Many people move from frail to pre-frail with consistent effort."
        ),
        "severely_frail": (
            "Your body needs significant support right now. Focus on gentle movement with your caregiver's help, "
            "eating well, and staying comfortable. Even small movements help maintain your strength."
        ),
    },
    "balance": (
        "Balance is the foundation of safe movement. Good balance prevents falls and helps you walk confidently.\n\n"
        "**Tips for Better Balance:**\n"
        "• Practice standing on one foot (hold a chair)\n"
        "• Walk heel-to-toe along a straight line\n"
        "• Stand up slowly — don't rush\n"
        "• Keep your home well-lit and clutter-free"
    ),
    "falls_prevention": (
        "1 in 3 adults over 65 experience falls each year. Most falls are preventable.\n\n"
        "**At Home:**\n"
        "• Remove loose rugs and clutter\n"
        "• Install grab bars in the bathroom\n"
        "• Keep lights on at night (use night lights)\n"
        "• Wear non-slip shoes or slippers\n\n"
        "**When Walking:**\n"
        "• Take your time — don't rush\n"
        "• Use handrails on stairs\n"
        "• Be careful on wet floors\n"
        "• Consider using a walking aid if recommended"
    ),
    "nutrition": (
        "Good nutrition is essential for maintaining strength and preventing frailty.\n\n"
        "**Key Points:**\n"
        "• Eat protein at every meal (fish, chicken, tofu, eggs)\n"
        "• Drink 6-8 glasses of water daily\n"
        "• Eat plenty of vegetables and fruits\n"
        "• Consider vitamin D supplements (ask your doctor)\n"
        "• Don't skip meals"
    ),
}

# ── Monitoring Templates ──────────────────────────────────────────────

MONITORING_TEMPLATES: dict[str, str] = {
    "robust": "Continue daily exercises. Recheck in 14 days.",
    "pre_frail": "Focus on balance and gait exercises. Monitor weekly. Recheck in 14 days.",
    "frail": "Daily gentle exercises essential. Caregiver should monitor. Recheck in 14 days.",
    "severely_frail": "Prioritize safety. Caregiver supervision recommended. Recheck in 7 days.",
}


# ── Helper Functions ──────────────────────────────────────────────────


def get_exercise_plan(tier: str, deficits: list[str] | None = None, issues: list[str] | None = None, language: str = "en") -> dict:
    """Get exercise plan for a tier, optionally refined by deficits and detected issues."""
    plans = _get_lang_plans(language)
    plan = plans.get(tier, plans["pre_frail"]).copy()

    # Add priority exercises based on deficits
    priority = []
    if deficits:
        for deficit in deficits:
            priority.extend(DEFICIT_EXERCISES.get(deficit, []))
    if issues:
        for issue in issues:
            priority.extend(ISSUE_EXERCISES.get(issue, []))

    if priority:
        # Deduplicate and put priority exercises first
        seen = set()
        ordered = []
        for ex in priority:
            if ex not in seen:
                seen.add(ex)
                ordered.append(ex)
        for ex in plan["exercises"]:
            if ex not in seen:
                seen.add(ex)
                ordered.append(ex)
        plan["exercises"] = ordered
        plan["focus_areas"] = list(dict.fromkeys(deficits or []))

    return plan


def get_sleep_advice(risk_level: str) -> str:
    """Get sleep content for a risk level."""
    return SLEEP_CONTENT.get(risk_level, SLEEP_CONTENT["low"])


def get_education(topic: str, tier: str | None = None) -> str:
    """Get educational content by topic, optionally tier-specific."""
    content = EDUCATION_CONTENT.get(topic)
    if content is None:
        return "Information about this topic is not available yet."
    if isinstance(content, dict) and tier:
        return content.get(tier, content.get("pre_frail", str(content)))
    if isinstance(content, dict):
        return str(next(iter(content.values())))
    return content


def get_monitoring_notes(tier: str) -> str:
    """Get monitoring template for a tier."""
    return MONITORING_TEMPLATES.get(tier, MONITORING_TEMPLATES["pre_frail"])


def build_care_plan_content(plan_type: str, tier: str, risks: dict[str, str] | None = None, deficits: list[str] | None = None, issues: list[str] | None = None, language: str = "en") -> str:
    """Build care plan content as JSON string for storage in care_plans table."""
    if plan_type == "exercise":
        return json.dumps(get_exercise_plan(tier, deficits, issues, language), ensure_ascii=False)
    elif plan_type == "sleep":
        risk = (risks or {}).get("sleep_risk", "low")
        return json.dumps({"type": "sleep", "risk_level": risk, "content": get_sleep_advice(risk)}, ensure_ascii=False)
    elif plan_type == "education":
        return json.dumps({"type": "education", "content": get_education("frailty", tier)}, ensure_ascii=False)
    elif plan_type == "monitoring":
        return json.dumps({"type": "monitoring", "content": get_monitoring_notes(tier)}, ensure_ascii=False)
    return ""
